
GGV2_REGION="eu-central-1"
GGV2_DATA_EP="a4kk9miw5vnsy-ats.iot.eu-central-1.amazonaws.com"
GGV2_CRED_EP="c3f98lqdkl3pg2.credentials.iot.eu-central-1.amazonaws.com"
GGV2_TES_RALIAS="GreengrassCoreTokenExchangeRoleAlias"
