version: 0.2
run-as: yoctouser

env:
  shell: bash
  # HOME is set to /root even when running as a non-root user.
  variables:
    HOME: "/home/yoctouser"

phases:
  pre_build:
    run-as: root
    commands:
      - chown -R yoctouser /sstate-cache
      - chown -R yoctouser /downloads
      - chmod 755 /sstate-cache
      - chmod 755 /downloads
  build:
    commands:
      - repo init -u $CODEBUILD_SRC_DIR -b main -m manifest.xml
      - repo sync
      - source meta-agl/scripts/aglsetup.sh  -f -m biga-goldbox -b $TMP_DIR
      - echo copy site.conf
      - cp $CODEBUILD_SRC_DIR/site.conf $TMP_DIR/conf/
      - echo get claim certs
      - aws secretsmanager get-secret-value --secret-id NxpGoldboxBigaPipeline_claim.cert.pem --query SecretBinary --output text | base64 --decode > $CODEBUILD_SRC_DIR/external/meta-aws/recipes-iot/aws-iot-greengrass/files/claim.cert.pem
      - aws secretsmanager get-secret-value --secret-id NxpGoldboxBigaPipeline_claim.pkey.pem --query SecretBinary --output text | base64 --decode > $CODEBUILD_SRC_DIR/external/meta-aws/recipes-iot/aws-iot-greengrass/files/claim.pkey.pem
      - aws secretsmanager get-secret-value --secret-id NxpGoldboxBigaPipeline_claim.root.pem --query SecretBinary --output text | base64 --decode > $CODEBUILD_SRC_DIR/external/meta-aws/recipes-iot/aws-iot-greengrass/files/claim.root.pem
      - echo build started at `date`
      - bitbake  aws-biga-image
      - bitbake  aws-biga-image -c populate_sdk
      - echo build finished at `date`
  post_build:
    commands:
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /sstate-cache -atime +30 -type f -delete
      # only delete empty dirs
      - find /sstate-cache -atime +30 -type d -empty -delete
      # Prune old files in our EFS Mounts, that are not accessed by this or any build within 30 days
      - find /downloads -atime +30 -type f -delete
      # only delete empty dirs
      - find /downloads -atime +30 -type d -empty -delete

artifacts:
  discard-paths: true
  files:
    - $TMP_DIR/tmp/deploy/images/s32g274ardb2/*.sdcard
    - $TMP_DIR/tmp/deploy/sdk/*.sh
